/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Nimta = Nimta1 & Nimta2;
export type Nimta1 = NimtaBase;

export interface NimtaBase {
    name: string;
    relative: string[];
}
export interface Nimta2 {
    _id: string;
}
