/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NimtaList = Nimta[];
export type Nimta = Nimta1 & Nimta3;
export type Nimta1 = NimtaBase & Nimta2;

export interface NimtaBase {
    name: string;
}
export interface Nimta2 {
    _id: string;
}
export interface Nimta3 {
    relative: string[];
}
