/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Pariwar = Pariwar1 & Pariwar2;
export type Pariwar1 = PariwarBase;

export interface PariwarBase {
    name: string;
}
export interface Pariwar2 {
    _id: string;
}
