/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Relative = Relative1 & Relative2;
export type Relative1 = RelativeBase;
export type RelativeList = Relative[];

export interface RelativeBase {
    firstName: string;
    lastName: string;
    fathersName: string;
    address: string;
    nickName: string;
    phoneNumber: string;
    details: string;
    assignTo: string;
}
export interface Relative2 {
    _id: string;
    pariwarId: string;
}
