/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Relative = Relative1 & Relative3;
export type Relative1 = RelativeBase & Relative2;

export interface RelativeBase {
    firstName: string;
    lastName: string;
    fathersName: string;
    address: string;
    nickName: string;
    phoneNumber: string;
}
export interface Relative2 {
    _id: string;
    pariwarId: string;
}
export interface Relative3 {
    details?: string;
    assignTo?: string;
}
